# Databricks notebook source
# Schema definitions for GLD harmonized tables

#' Get the standard GLD harmonized schema
#'
#' @return A named list where names are column names and values are data types
get_gld_schema <- function() {
  list(
    countrycode = "string",
    survname = "string",
    survey = "string",
    quarter = "string",
    icls_v = "string",
    isced_version = "string",
    isco_version = "string",
    isic_version = "string",
    year = "integer",
    vermast = "string",
    veralt = "string",
    harmonization = "string",
    int_year = "integer",
    int_month = "integer",
    hhid = "string",
    pid = "string",
    weight = "double",
    weight_m = "double",
    weight_q = "double",
    psu = "string",
    ssu = "string",
    wave = "string",
    panel = "string",
    visit_no = "integer",
    urban = "integer",
    subnatidsurvey = "string",
    strata = "string",
    hsize = "double",
    age = "double",
    male = "integer",
    relationharm = "integer",
    relationcs = "string",
    marital = "integer",
    eye_dsablty = "integer",
    hear_dsablty = "integer",
    walk_dsablty = "integer",
    conc_dsord = "integer",
    slfcre_dsablty = "integer",
    comm_dsablty = "integer",
    migrated_mod_age = "integer",
    migrated_ref_time = "integer",
    migrated_binary = "integer",
    migrated_years = "integer",
    migrated_from = "integer",
    migrated_from_cat = "integer",
    migrated_from_code = "integer",
    migrated_from_country = "string",
    migrated_reason = "integer",
    ed_mod_age = "integer",
    school = "integer",
    literacy = "integer",
    educy = "integer",
    educat7 = "integer",
    educat5 = "integer",
    educat4 = "integer",
    educat_orig = "string",
    educat_isced = "double",
    vocational = "integer",
    vocational_type = "integer",
    vocational_length_l = "integer",
    vocational_length_u = "integer",
    vocational_field = "integer",
    vocational_financed = "integer",
    minlaborage = "double",
    lstatus = "integer",
    potential_lf = "integer",
    underemployment = "integer",
    nlfreason = "integer",
    unempldur_l = "double",
    unempldur_u = "double",
    empstat = "integer",
    ocusec = "integer",
    industry_orig = "string",
    industrycat_isic = "string",
    industrycat10 = "integer",
    industrycat4 = "integer",
    occup_orig = "string",
    occup_isco = "string",
    occup_skill = "integer",
    occup = "integer",
    wage_no_compen = "double",
    unitwage = "integer",
    whours = "double",
    wmonths = "double",
    wage_total = "double",
    contract = "integer",
    healthins = "integer",
    socialsec = "integer",
    union = "integer",
    firmsize_l = "double",
    firmsize_u = "double",
    empstat_2 = "integer",
    ocusec_2 = "integer",
    industry_orig_2 = "string",
    industrycat_isic_2 = "integer",
    industrycat10_2 = "integer",
    industrycat4_2 = "integer",
    occup_orig_2 = "string",
    occup_isco_2 = "string",
    occup_skill_2 = "integer",
    occup_2 = "integer",
    wage_no_compen_2 = "double",
    unitwage_2 = "integer",
    whours_2 = "double",
    wmonths_2 = "double",
    wage_total_2 = "double",
    firmsize_l_2 = "double",
    firmsize_u_2 = "double",
    t_hours_others = "double",
    t_wage_nocompen_others = "double",
    t_wage_others = "double",
    t_hours_total = "double",
    t_wage_nocompen_total = "double",
    t_wage_total = "double",
    lstatus_year = "integer",
    potential_lf_year = "integer",
    underemployment_year = "integer",
    nlfreason_year = "integer",
    unempldur_l_year = "double",
    unempldur_u_year = "double",
    empstat_year = "integer",
    ocusec_year = "integer",
    industry_orig_year = "string",
    industrycat_isic_year = "integer",
    industrycat10_year = "integer",
    industrycat4_year = "integer",
    occup_orig_year = "string",
    occup_isco_year = "string",
    occup_skill_year = "integer",
    occup_year = "integer",
    wage_no_compen_year = "double",
    unitwage_year = "integer",
    whours_year = "double",
    wmonths_year = "double",
    wage_total_year = "double",
    contract_year = "integer",
    healthins_year = "integer",
    socialsec_year = "integer",
    union_year = "integer",
    firmsize_l_year = "double",
    firmsize_u_year = "double",
    empstat_2_year = "integer",
    ocusec_2_year = "integer",
    industry_orig_2_year = "string",
    industrycat_isic_2_year = "integer",
    industrycat10_2_year = "integer",
    industrycat4_2_year = "integer",
    occup_orig_2_year = "string",
    occup_isco_2_year = "string",
    occup_skill_2_year = "integer",
    occup_2_year = "integer",
    wage_no_compen_2_year = "double",
    unitwage_2_year = "integer",
    whours_2_year = "double",
    wmonths_2_year = "double",
    wage_total_2_year = "double",
    firmsize_l_2_year = "double",
    firmsize_u_2_year = "double",
    t_hours_others_year = "double",
    t_wage_nocompen_others_year = "double",
    t_wage_others_year = "double",
    t_hours_total_year = "double",
    t_wage_nocompen_total_year = "double",
    t_wage_total_year = "double",
    njobs = "double",
    t_hours_annual = "double",
    linc_nc = "double",
    laborincome = "double"
  )
}


#' Check if a column name matches the subnational pattern
#'
#' @param column_name Name of the column to check
#' @return TRUE if the column matches subnational pattern, FALSE otherwise
is_subnational_column <- function(column_name) {
  grepl("^subnatid\\d+(_prev)?$", column_name)
}


#' Check if a column name matches the GAUL pattern
#'
#' @param column_name Name of the column to check
#' @return TRUE if the column matches GAUL pattern, FALSE otherwise
is_gaul_column <- function(column_name) {
  grepl("^gaul_adm\\d+_code$", column_name)
}


#' Check if a column is a dynamic column (subnational or GAUL)
#'
#' @param column_name Name of the column to check
#' @return TRUE if the column is dynamic, FALSE otherwise
is_dynamic_column <- function(column_name) {
  is_subnational_column(column_name) || is_gaul_column(column_name)
}
